import { createTauriTest } from '@srsholmes/tauri-playwright'

export const { test, expect } = createTauriTest({
  devUrl: 'http://localhost:5173',
  ipcMocks: {
    get_projects: () => [],
    create_project: (args: any) => ({
      id: 'test-proj-1',
      name: args?.name || 'New Project',
      description: args?.description || '',
      background: args?.background || '',
      settings: args?.settings || '{}',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted_at: null,
    }),
    get_project: (args: any) => ({
      id: args?.id || 'test-proj-1',
      name: 'Test Project',
      description: '',
      background: '',
      settings: '{"serverUrl":"http://localhost:3000","token":"test-token"}',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted_at: null,
    }),
    get_knowledge_articles: () => [],
    create_knowledge_article: (args: any) => ({
      id: 'test-article-1',
      project_id: args?.projectId || 'test-proj-1',
      title: args?.title || 'Untitled',
      content: args?.content || '',
      content_json: '{}',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }),
    get_knowledge_article: (args: any) => ({
      id: args?.id || 'test-article-1',
      project_id: 'test-proj-1',
      title: 'Test Article',
      content: '# Hello',
      content_json: '{}',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }),
    get_setting: () => null,
    set_setting: () => null,
    load_settings: () => ({}),
    get_whiteboards: () => [],
    get_external_links: () => [],
    get_project_files: () => [],
  },
  mcpSocket: '/tmp/tauri-playwright.sock',
})
